spring.application.name=GestionTramites

spring.datasource.url=jdbc:postgresql://localhost:5432/catalogo_servicios_personal
spring.datasource.username=postgres
spring.datasource.password=root123456

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080